include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-cQME

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-meditations-summary-39dd410c-17f1-4296-9910-c3d69a7368a4
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-cQME
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-meditations-summary
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetMeditationsSummary
    packageref:
      name: get-meditations-summary-39dd410c-17f1-4296-9910-c3d69a7368a4
      namespace: default
  resources: {}
  secrets: null
