include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-Wg0N

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-longest-sleep-trend-cd841e18-feef-4d1c-a47c-ca3d64013a49
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-Wg0N
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-05-16T12:26:03Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-longest-sleep-trend
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetLongestSleepTrend
    packageref:
      name: get-longest-sleep-trend-cd841e18-feef-4d1c-a47c-ca3d64013a49
      namespace: default
  resources: {}
  secrets: null
