include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-jSuY

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: create-user-c3745eb6-0fd2-4c02-b7b5-5305e1eb5dd0
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-jSuY
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:44Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: create-user
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: CreateUser
    packageref:
      name: create-user-c3745eb6-0fd2-4c02-b7b5-5305e1eb5dd0
      namespace: default
  resources: {}
  secrets: null
