include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-FL0h

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: register-device-09c12a71-3afc-4f47-80c0-2268bedc5ced
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-FL0h
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:48Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: register-device
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: RegisterDevice
    packageref:
      name: register-device-09c12a71-3afc-4f47-80c0-2268bedc5ced
      namespace: default
  resources: {}
  secrets: null
