include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-23R0

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-alerts-a5c04ce5-429b-44f3-960d-74d6b95cbdd7
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-23R0
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:22Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-alerts
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListAlerts
    packageref:
      name: list-alerts-a5c04ce5-429b-44f3-960d-74d6b95cbdd7
      namespace: default
  resources: {}
  secrets: null
