include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-pP7i

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: verify-otp-e4537f6f-d797-4262-918a-552f92af157d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-pP7i
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: verify-otp
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: VerifyOtp
    packageref:
      name: verify-otp-e4537f6f-d797-4262-918a-552f92af157d
      namespace: default
  resources: {}
  secrets: null
