include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-agbR

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: create-alert-escalation-3c77f9fb-cd6f-44e7-9b92-16ff6adc8207
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-agbR
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-28T12:13:21Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: create-alert-escalation
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: CreateAlertEscalation
    packageref:
      name: create-alert-escalation-3c77f9fb-cd6f-44e7-9b92-16ff6adc8207
      namespace: default
  resources: {}
  secrets: null
