include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-dEsg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: create-op-33fb13ad-f608-468a-8af7-2458c0aefca5
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-dEsg
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:31Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: create-op
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: CreateOp
    packageref:
      name: create-op-33fb13ad-f608-468a-8af7-2458c0aefca5
      namespace: default
  resources: {}
  secrets: null
