include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-cxun

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: unregister-device-04bfff90-423f-4aa9-8ef8-8d23c516d69e
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-cxun
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:55Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: unregister-device
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UnregisterDevice
    packageref:
      name: unregister-device-04bfff90-423f-4aa9-8ef8-8d23c516d69e
      namespace: default
  resources: {}
  secrets: null
