include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-VTnI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-alert-rule-0629700b-5518-4582-9f8c-bd0146460651
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-VTnI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-28T12:13:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-alert-rule
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UpdateAlertRule
    packageref:
      name: update-alert-rule-0629700b-5518-4582-9f8c-bd0146460651
      namespace: default
  resources: {}
  secrets: null
