include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-VRzu

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-user-properties-24995c10-e03b-42d6-a448-607670986345
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-VRzu
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T04:57:55Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-user-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UpdateUserProperties
    packageref:
      name: update-user-properties-24995c10-e03b-42d6-a448-607670986345
      namespace: default
  resources: {}
  secrets: null
