include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-yzIe

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-alert-escalations-dea38d69-d5da-4050-98d6-a32644c7ea08
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-yzIe
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-05-01T09:32:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-alert-escalations
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListAlertEscalations
    packageref:
      name: list-alert-escalations-dea38d69-d5da-4050-98d6-a32644c7ea08
      namespace: default
  resources: {}
  secrets: null
