include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-JkW4

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-orgs-9f84fde7-003d-4301-a871-cde48cb9639d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-JkW4
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-orgs
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListOrgs
    packageref:
      name: list-orgs-9f84fde7-003d-4301-a871-cde48cb9639d
      namespace: default
  resources: {}
  secrets: null
