include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-u1EX

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: create-org-40d5c0ce-a117-403e-8063-2ee0c1f48a91
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-u1EX
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:25Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: create-org
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: CreateOrg
    packageref:
      name: create-org-40d5c0ce-a117-403e-8063-2ee0c1f48a91
      namespace: default
  resources: {}
  secrets: null
