include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-c2Rv

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: change-role-to-op-2a81ebce-3524-4849-b3c1-c3f2e065b2bd
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-c2Rv
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:03Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: change-role-to-op
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ChangeRoleToOp
    packageref:
      name: change-role-to-op-2a81ebce-3524-4849-b3c1-c3f2e065b2bd
      namespace: default
  resources: {}
  secrets: null
