include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-CvT6

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-device-properties-8ea150e8-e235-4e37-836a-af05242be801
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-CvT6
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-18T12:46:26Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-device-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetDeviceProperties
    packageref:
      name: get-device-properties-8ea150e8-e235-4e37-836a-af05242be801
      namespace: default
  resources: {}
  secrets: null
