include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-YRWA

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: delete-auth-0ef4c06e-7614-4be5-a0b1-afbae9e6457a
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-YRWA
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-27T12:38:10Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: delete-auth
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: DeleteAuth
    packageref:
      name: delete-auth-0ef4c06e-7614-4be5-a0b1-afbae9e6457a
      namespace: default
  resources: {}
  secrets: null
