include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-InY2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-session-durations-6b0365ed-2978-42ec-8f74-48e19d58fcfe
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-InY2
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-05-08T19:04:43Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-session-durations
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetSessionDurations
    packageref:
      name: get-session-durations-6b0365ed-2978-42ec-8f74-48e19d58fcfe
      namespace: default
  resources: {}
  secrets: null
