include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-HLt6

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-ops-84ef282f-26fb-43e4-aa19-c47a4719145e
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-HLt6
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:23Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-ops
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListOps
    packageref:
      name: list-ops-84ef282f-26fb-43e4-aa19-c47a4719145e
      namespace: default
  resources: {}
  secrets: null
