include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-yHGb

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: create-api-key-d8293730-5e46-4738-a078-134c0dec7d1a
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-yHGb
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:28Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: create-api-key
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: CreateKey
    packageref:
      name: create-api-key-d8293730-5e46-4738-a078-134c0dec7d1a
      namespace: default
  resources: {}
  secrets: null
