include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-1azm

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-device-properties-a79462d0-e63b-446d-a5db-1142d89fc7de
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-1azm
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-18T12:23:38Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: add-device-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: AddDeviceProperties
    packageref:
      name: add-device-properties-a79462d0-e63b-446d-a5db-1142d89fc7de
      namespace: default
  resources: {}
  secrets: null
