include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-OPV8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-session-c5505015-3c03-458e-be6c-4b709644c3dc
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-OPV8
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-17T20:04:27Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-session
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetUserSession
    packageref:
      name: get-user-session-c5505015-3c03-458e-be6c-4b709644c3dc
      namespace: default
  resources: {}
  secrets: null
