include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-eNpg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-users-59a3d27a-5c66-4fca-a147-6c1080a13573
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-eNpg
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-users
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListUsers
    packageref:
      name: list-users-59a3d27a-5c66-4fca-a147-6c1080a13573
      namespace: default
  resources: {}
  secrets: null
