include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-R9dW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-session-events-7b78d593-9a9e-41b3-9487-052b74c1ae53
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-R9dW
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-23T05:51:08Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-session-events
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetUserSessionEvents
    packageref:
      name: get-user-session-events-7b78d593-9a9e-41b3-9487-052b74c1ae53
      namespace: default
  resources: {}
  secrets: null
