include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-TKEZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-org-properties-073fe9f5-a711-40a1-9d1d-e253a3c4a257
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-TKEZ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T04:57:41Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-org-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UpdateOrgProperties
    packageref:
      name: update-org-properties-073fe9f5-a711-40a1-9d1d-e253a3c4a257
      namespace: default
  resources: {}
  secrets: null
