include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-SoxG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: verify-auth-be264ea1-7328-459e-9a6a-e095693140b2
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-SoxG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:12Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: verify-auth
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: VerifyAuth
    packageref:
      name: verify-auth-be264ea1-7328-459e-9a6a-e095693140b2
      namespace: default
  resources: {}
  secrets: null
