include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-njFq

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: change-role-to-auth-f1206351-5dfe-4054-923f-ed2cf7774152
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-njFq
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:10Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: change-role-to-auth
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ChangeRoleToAuth
    packageref:
      name: change-role-to-auth-f1206351-5dfe-4054-923f-ed2cf7774152
      namespace: default
  resources: {}
  secrets: null
