include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-IcTQ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-org-properties-52c23415-5c63-44b9-95c6-ea6b07eaa247
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-IcTQ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T04:58:01Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-org-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListOrgProperties
    packageref:
      name: list-org-properties-52c23415-5c63-44b9-95c6-ea6b07eaa247
      namespace: default
  resources: {}
  secrets: null
