include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-YXQP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-user-properties-637450c1-5dfb-40e2-9cb4-0dc879e01dc1
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-YXQP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T04:58:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-user-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListUserProperties
    packageref:
      name: list-user-properties-637450c1-5dfb-40e2-9cb4-0dc879e01dc1
      namespace: default
  resources: {}
  secrets: null
