include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-uQaG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: request-otp-1280a34f-a43d-4d74-a213-bf3cb87ec4f5
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-uQaG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:54:59Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: request-otp
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: RequestOtp
    packageref:
      name: request-otp-1280a34f-a43d-4d74-a213-bf3cb87ec4f5
      namespace: default
  resources: {}
  secrets: null
