include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-uzrl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-sleep-trend-48dc9cd9-6421-4c07-a1f7-28954e5db463
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-uzrl
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-05-15T12:26:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-sleep-trend
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetSleepTrend
    packageref:
      name: get-sleep-trend-48dc9cd9-6421-4c07-a1f7-28954e5db463
      namespace: default
  resources: {}
  secrets: null
