include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-QZZR

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-user-83443a84-4536-461d-9158-15430f8b2d67
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-QZZR
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:50Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: add-user
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: AddUser
    packageref:
      name: add-user-83443a84-4536-461d-9158-15430f8b2d67
      namespace: default
  resources: {}
  secrets: null
