include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-VSnw

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-devices-175555fd-90fb-4435-85dd-cc1093ec8549
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-VSnw
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-devices
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListDevices
    packageref:
      name: list-devices-175555fd-90fb-4435-85dd-cc1093ec8549
      namespace: default
  resources: {}
  secrets: null
