include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-9hZd

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-alert-75edcbff-56f8-481f-85be-db33a3d44e6f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-9hZd
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-28T12:14:27Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-alert
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UpdateAlert
    packageref:
      name: update-alert-75edcbff-56f8-481f-85be-db33a3d44e6f
      namespace: default
  resources: {}
  secrets: null
