include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-bFe3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-activities-982a9aae-580e-4755-9aa5-f9a14e4f6208
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-bFe3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-13T07:09:22Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-activities
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListActivities
    packageref:
      name: list-activities-982a9aae-580e-4755-9aa5-f9a14e4f6208
      namespace: default
  resources: {}
  secrets: null
