include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-iqcs

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-session-5fac7b5c-cf54-4e83-8e5e-a823aaee0434
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-iqcs
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:58:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-session
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetSession
    packageref:
      name: get-session-5fac7b5c-cf54-4e83-8e5e-a823aaee0434
      namespace: default
  resources: {}
  secrets: null
