include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-2UuB

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: pair-device-8ddaf7d8-9504-45db-aece-eed9fa1f7715
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-2UuB
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:58:02Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: pair-device
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: PairDevice
    packageref:
      name: pair-device-8ddaf7d8-9504-45db-aece-eed9fa1f7715
      namespace: default
  resources: {}
  secrets: null
