include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-f8G8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-api-keys-2b0363c0-7d22-4346-96e0-1189de5477e4
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-f8G8
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:35Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-api-keys
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListKeys
    packageref:
      name: list-api-keys-2b0363c0-7d22-4346-96e0-1189de5477e4
      namespace: default
  resources: {}
  secrets: null
