include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-QJeZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: create-device-a2eee6ea-0636-4399-9e16-daca3dca81d9
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-QJeZ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:42Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: create-device
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: CreateDevice
    packageref:
      name: create-device-a2eee6ea-0636-4399-9e16-daca3dca81d9
      namespace: default
  resources: {}
  secrets: null
