include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-Zxdb

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-alert-escalation-0a08954b-970a-43c6-8c93-508f6a762657
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-Zxdb
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-28T12:13:35Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-alert-escalation
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UpdateAlertEscalation
    packageref:
      name: update-alert-escalation-0a08954b-970a-43c6-8c93-508f6a762657
      namespace: default
  resources: {}
  secrets: null
