include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-nvau

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-latest-alerts-190c9090-d36a-4816-8187-e10e3752ad2e
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-nvau
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-26T09:28:55Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-latest-alerts
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListLatestAlerts
    packageref:
      name: list-latest-alerts-190c9090-d36a-4816-8187-e10e3752ad2e
      namespace: default
  resources: {}
  secrets: null
