include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-X7Ep

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-users-summary-19c1cdeb-0b8e-4b41-8f9b-71043e6b228a
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-X7Ep
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:42Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-users-summary
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListUserSummary
    packageref:
      name: list-users-summary-19c1cdeb-0b8e-4b41-8f9b-71043e6b228a
      namespace: default
  resources: {}
  secrets: null
