include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-BbID

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: unpair-device-a54564d3-3eaf-4e7c-914a-9860bc048fcf
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-BbID
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:58:08Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: unpair-device
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UnpairDevice
    packageref:
      name: unpair-device-a54564d3-3eaf-4e7c-914a-9860bc048fcf
      namespace: default
  resources: {}
  secrets: null
