include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-Pjx3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-sleeps-summary-bf181c79-cede-41cd-bd74-e03a98bd0b6e
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-Pjx3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:57:08Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-sleeps-summary
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetSleepsSummary
    packageref:
      name: get-sleeps-summary-bf181c79-cede-41cd-bd74-e03a98bd0b6e
      namespace: default
  resources: {}
  secrets: null
