include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-4TtZ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-q-activity-counts-0df60188-b0cb-4310-938c-d84bb355107b
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-4TtZ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-17T20:03:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-q-activity-counts
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: GetQuarterActivityCounts
    packageref:
      name: get-q-activity-counts-0df60188-b0cb-4310-938c-d84bb355107b
      namespace: default
  resources: {}
  secrets: null
