include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-rj7C

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-op-properties-d6297e9c-eb40-4349-8506-d554ed76bd47
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-rj7C
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T04:57:48Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-op-properties
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: UpdateOpProperties
    packageref:
      name: update-op-properties-d6297e9c-eb40-4349-8506-d554ed76bd47
      namespace: default
  resources: {}
  secrets: null
