include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-eDq8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-user-baselines-19b0ae86-2e07-4bf2-a64a-46fe56d73fdb
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-eDq8
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-05-27T13:04:02Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-user-baselines
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListUserBaselines
    packageref:
      name: list-user-baselines-19b0ae86-2e07-4bf2-a64a-46fe56d73fdb
      namespace: default
  resources: {}
  secrets: null
