include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-oXlo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: list-users-meditations-62a0e439-aa98-460b-a4ca-790de93fb45f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-oXlo
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:56:55Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: list-users-meditations
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: ListUserMeditations
    packageref:
      name: list-users-meditations-62a0e439-aa98-460b-a4ca-790de93fb45f
      namespace: default
  resources: {}
  secrets: null
