include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-D6nY

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-op-0a097c75-0854-4edc-b073-f352d11e2898
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-D6nY
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:37Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: add-op
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: AddOp
    packageref:
      name: add-op-0a097c75-0854-4edc-b073-f352d11e2898
      namespace: default
  resources: {}
  secrets: null
