include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-mVFl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: refresh-token-6e00917b-dbbe-4733-b565-c40edc673db9
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-mVFl
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:57Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: refresh-token
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: RefreshToken
    packageref:
      name: refresh-token-6e00917b-dbbe-4733-b565-c40edc673db9
      namespace: default
  resources: {}
  secrets: null
