include:
- sens/ws/*
kind: ArchiveUploadSpec
name: sens-ws-CBR3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-org-bbbcca6e-d734-44ae-8891-7ef2c71b5f1f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://sens-ws-CBR3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-12T21:55:19Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: add-org
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  package:
    functionName: AddOrg
    packageref:
      name: add-org-bbbcca6e-d734-44ae-8891-7ef2c71b5f1f
      namespace: default
  resources: {}
  secrets: null
