apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: list-op-properties
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: list-op-properties
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/ops/{id}/properties/list
    tls: ""
  method: GET
  relativeurl: /api/ops/{id}/properties/list
