apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: change-role-to-op
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: change-role-to-op
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/roles/update/op
    tls: ""
  method: POST
  relativeurl: /api/roles/update/op
