apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: list-user-baselines
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: list-user-baselines
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/users/{id}/baselines/list
    tls: ""
  method: GET
  relativeurl: /api/users/{id}/baselines/list
