apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-user-dated-session
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-user-dated-session
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/users/{id}/dated-sessions/get
    tls: ""
  method: GET
  relativeurl: /api/users/{id}/dated-sessions/get
