apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: update-user-properties
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-user-properties
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/users/{id}/properties/update
    tls: ""
  method: POST
  relativeurl: /api/users/{id}/properties/update
