apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-users-sleep-count
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-users-sleep-count
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/users/sleeps/count
    tls: ""
  method: GET
  relativeurl: /api/users/sleeps/count
