apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: unregister-device
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: unregister-device
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/devices/unregister
    tls: ""
  method: POST
  relativeurl: /api/devices/unregister
