apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-user-session-events
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-user-session-events
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/sessions/{id}/events/get
    tls: ""
  method: GET
  relativeurl: /api/sessions/{id}/events/get
