apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: refresh-token
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: refresh-token
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/tokens/refresh
    tls: ""
  method: GET
  relativeurl: /api/tokens/refresh
