apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-q-activity-counts
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-q-activity-counts
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/org/q-activities/counts
    tls: ""
  method: GET
  relativeurl: /api/org/q-activities/counts
