apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: add-device-properties
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: add-device-properties
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/devices/properties/add
    tls: ""
  method: POST
  relativeurl: /api/devices/properties/add
