apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: request-user-reports
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: request-user-reports
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/users/{id}/report/request
    tls: ""
  method: POST
  relativeurl: /api/users/{id}/report/request
