apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: list-api-keys
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: list-api-keys
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/keys/list
    tls: ""
  method: POST
  relativeurl: /api/keys/list
