apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: verify-otp
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: verify-otp
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/otp/verify
    tls: ""
  method: POST
  relativeurl: /api/otp/verify
