apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-longest-sleep-trend
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-longest-sleep-trend
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/users/{id}/longest-trend/get
    tls: ""
  method: GET
  relativeurl: /api/users/{id}/longest-trend/get
