apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: create-op
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: create-op
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/ops/create
    tls: ""
  method: POST
  relativeurl: /api/ops/create
