apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: register-device
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: register-device
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/devices/register
    tls: ""
  method: POST
  relativeurl: /api/devices/register
