apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: update-alert-escalation
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-alert-escalation
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/alert-escalations/{id}/update
    tls: ""
  method: POST
  relativeurl: /api/alert-escalations/{id}/update
