apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: create-org
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: create-org
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/orgs/create
    tls: ""
  method: POST
  relativeurl: /api/orgs/create
